name = "remix-auth-jwt"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
  SESSION_SECRET = "s3cr3t"